### ISSUE TITLE
Adjust JSON render

### ISSUE THREAD

**Issue by smile-eh** [DIS-SIN/CORTEX#1]
The rendering of the JSON (ex: arrays for langs, etc) must be adjusted.

From line# 383 of neuron notes.

**Comment by mightyweasel** [comment]
Closed as no longer applicable. For the first end-to-end test with Evalhalla+CORTEX we're going to use Evalese in the messages (persisted likely in Kafka temporarily during demo phases) to reduce rework needed for the same end-user demonstration impact. The React version of player, designer, and dashboard will bypass the issue as the way we render will be entirely different.
