### ISSUE TITLE
Additional refactoring to seperate concerns

### ISSUE THREAD

**Issue by smile-eh** [DIS-SIN/CORTEX#14]
Refactor v2 library (to have init functions as well as enable feature)

Regression testing on V1

Build out enable feature functions so that code is loaded at proper time and doesn't unecesarily slow things.

Refactor basic designer to be distinct from advanced

Survey template storage
 - All of the surveys in one folder, build this into proper templates so it can be in one file

**Comment by mightyweasel** [comment]
V2 Lib created. Going to create a branch to push it to, we should give it a proper shakedown, but it should be easier to work on isolated parts. Caveat, there's still some tight coupling to fix, but that might be a moot point if we make progress on the React visualizer and player. 

v2:
- splits all major features into isolated components
- decouples the player, dashboard, and editor allowing independent modification
- adds additional test surveys for various upcoming demo/feedback-pilots
- adds /department command (autocomplete for dept)
- adds /location command (autocomplete for city)
- adds /dropdown command (pick one, but in select box)
- adds /classification command (autocomplete for classification)
- adds /language command (autocomplete for languages)
- adds Tableview dashboard for .tsv style export for Excel use

**Comment by mightyweasel** [comment]
Known bugs in this commit, the dropdown multilingual issues (where <option> allows no html, so our method for changing on the fly doesn't degrade nicely)

This will be addressed by another issue in the project tracker, card is already created.

**Comment by mightyweasel** [comment]
https://github.com/DIS-SIN/Evalhalla/tree/v2-lib-refactor branch deployed. Once reviewed we'll merge into master, then start building out in CORTEX

**Comment by mightyweasel** [comment]
Closed by accident, there's a few more items in this issue before closure:
* Build out enable/init functions

**Comment by mightyweasel** [comment]
Added /offering to autoc enable/init
Connected Registhor API to pull days offerings (might need to revisit when we have events and the rest)
Updated /scale /scale1-5 and /dropdown with bilingual features
