### ISSUE TITLE
Contact DMO for logistics (AMD ELDP)

### ISSUE THREAD

**Issue by smile-eh** [DIS-SIN/CORTEX#39]
W/ KEVIN G

--- Cloud one we're not fully ready for, so we will need a local thing
--- Jotunheimr (kafka, dockers, etc) running in cloud (if and how omar can do that). We need to use the one that we're certain work (rather than just confluent packages, but we cant control them fully)
--- If we can revise: 1. Dynamically Create a View of Material UI components insert into the tree.

**Comment by mightyweasel** [comment]
Local deployment version ready per Nghia. If we need to local demo we can, but we're getting close on the CORTEX integration. If we can nail down the last cloud pieces we will be in good shape.

**Comment by smile-eh** [comment]
Running with ALDP survey until otherwise informed
