### ISSUE TITLE
Release refactored V2 code (see the survey we’re gonna use)

### ISSUE THREAD

**Issue by smile-eh** [DIS-SIN/CORTEX#49]

**Comment by mightyweasel** [comment]
Created branch v2-lib-refactor on https://github.com/DIS-SIN/Evalhalla/ once we test it to make sure everything is solid we can merge in and then start splitting up the load. 

I've kept the v1 backwards compatible for now (just while the last of the super-early-access pilots get their data and finish up, but v2 can safely be worked on worry free)
