### ISSUE TITLE
HTML / JSON injection issue with languages

### ISSUE THREAD

**Issue by smile-eh** [DIS-SIN/CORTEX#59]
Evalhalla-designer's parser is incorrectly adding HTML when generating JSON.

Language tags ('/en', '/fr') replacement is supposed to happen for HTML generation, however it is also happening for JSON generation.

**Comment by mightyweasel** [comment]
This is fixed with the CORTEX json format. When we start consuming Kafka messages we should be able to avoid the issue, or be able to render straight from the payload
